name: OmniAssist AI CI

on:
  # Se activa al hacer push directo a las ramas principales
  push:
    branches: [ main, master ]
  
  # Se activa cuando se crea o actualiza un Pull Request hacia estas ramas
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

jobs:
  validate-and-build:
    name: Validate, Type-Check & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Type-Check
        run: npx tsc --noEmit
        # Este paso es crítico para asegurar que no hay errores de tipos en el PR

      - name: Build Web Application
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload Build Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/
          retention-days: 7

  android-sync:
    name: Capacitor Android Sync
    needs: validate-and-build
    runs-on: ubuntu-latest
    # Solo sincronizamos con Android cuando el código ya ha sido mergeado a main/master
    if: github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist/

      - name: Prepare Capacitor Android
        run: |
          npx cap sync android
